Разметка внутренней страницы
htmlacademy-htmlcss/1558021-technomart-29 pull request #2
Opened 2020-09-11 17:38 UTC by vitaliiguziaev

---
:mortar_board: [Разметка главной страницы](https://up.htmlacademy.ru/htmlcss/29/user/1558021/tasks/2)

---
:mortar_board: [Разметка внутренней страницы](https://up.htmlacademy.ru/htmlcss/29/user/1558021/tasks/3)

2020-09-11 21:25 UTC, kosovych requested changes

2020-09-11 21:25 UTC, kosovych commented on index.html
> +          </p>
хороший паттерн делать название товара ссылкой на страницу этого товара

2020-09-11 21:25 UTC, kosovych commented on index.html
> +          <button type="button">25500 Р.</button>
это не кнопка по меньшей мере из-за того, что в ТЗ не прописано взаимодействие с этим элементом

2020-09-11 21:25 UTC, kosovych commented on index.html
> +      <p>Популярные производители: <a href="">все производители</a></p>
не нужно дублировать контент. заголовка и ссылки будет достаточно

2020-09-11 21:25 UTC, kosovych commented on index.html
> +    </section>
разметьте блоки с Гарантией и доставкой (в скрытых слоях макета есть)

2020-09-11 21:25 UTC, kosovych commented on index.html
> +        +7 (812) 555-05-55
телефон это ссылка с соотв. протоколом

2020-09-11 21:25 UTC, kosovych commented on index.html
> +      <a href="https://htmlacademy.ru">htmlacademy.ru</a>
ссылка не соотв. ТЗ https://up.htmlacademy.ru/htmlcss/29/project/technomart#technomart-3-5

2020-09-11 21:25 UTC, kosovych commented on index.html
>  <!DOCTYPE html>
проверьте валидность HTML здесь https://validator.w3.org/#validate_by_input

2020-09-11 21:25 UTC, kosovych commented on index.html
> +        </li>
это уже другой список по смыслу

2020-09-13 19:39 UTC, vitaliiguziaev commented on index.html
> +          <button type="button">25500 Р.</button>
Сделал линкой

2020-09-13 19:39 UTC, vitaliiguziaev commented on index.html
> +          </p>
Сделал линкой

2020-09-13 19:40 UTC, vitaliiguziaev commented on index.html
> +      <p>Популярные производители: <a href="">все производители</a></p>
Оставил заголовок, иначе валидатор показывает ворнинг.
Правильно поступил?

2020-09-13 19:40 UTC, vitaliiguziaev commented on index.html
> +    </section>
Сделал

2020-09-13 19:40 UTC, vitaliiguziaev commented on index.html
> +        +7 (812) 555-05-55
Поправил

2020-09-13 19:41 UTC, vitaliiguziaev commented on index.html
> +      <a href="https://htmlacademy.ru">htmlacademy.ru</a>
Исправил

2020-09-13 19:41 UTC, vitaliiguziaev commented on index.html
>  <!DOCTYPE html>
Сделал

2020-09-13 19:41 UTC, vitaliiguziaev commented on index.html
> +        </li>
Разделил списки

2020-09-14 07:15 UTC, kosovych requested changes

2020-09-14 07:15 UTC, kosovych commented on catalog.html
> +                <p>Производители:</p>
для разделения формы на разделы лучше подойдет fieldset

2020-09-14 07:15 UTC, kosovych commented on catalog.html
> +            <ul>
забыл кнопки порядка сортировки

2020-09-14 07:15 UTC, kosovych commented on index.html
> +      <p>Популярные производители: <a href="">все производители</a></p>
в параграфе "Популярные производители:" лишнее

2020-09-14 07:15 UTC, kosovych commented on index.html
> +    </section>
здесь можно добавить больше семантики. сделайте каждый слайд секцией со своим заголовком и текстом, а ссылки сделайте якорями к этой секции

2020-09-14 07:15 UTC, kosovych commented on index.html
> +        <figcaption><button type="button">Заблудились? Напишите нам!</button></figcaption>
очень странная и сложная конструкция получилась (тем более что даже по ТЗ кнопка "Заблудились..." не связана с картой, а открывает модальное окно). сделайте проще (просто уберите figure и figcaption)

2020-09-16 20:33 UTC, vitaliiguziaev commented on index.html
> +      <p>Популярные производители: <a href="">все производители</a></p>
убрал

2020-09-16 20:34 UTC, vitaliiguziaev commented on catalog.html
> +                <p>Производители:</p>
добавил fieldset(s)

2020-09-16 20:34 UTC, vitaliiguziaev commented on catalog.html
> +            <ul>
добавил

2020-09-16 20:34 UTC, vitaliiguziaev commented on index.html
> +    </section>
исправил

2020-09-16 20:34 UTC, vitaliiguziaev commented on index.html
> +        <figcaption><button type="button">Заблудились? Напишите нам!</button></figcaption>
удалил лишнее

2020-09-17 06:11 UTC, merged